# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/project/golden/example6/project_1.srcs/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xci
# IP: The module: 'system_microblaze_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: E:/project/golden/example6/project_1.srcs/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xci
# IP: The module: 'system_microblaze_0_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc_debug.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: e:/project/golden/example6/project_1.gen/sources_1/bd/system/ip/system_microblaze_0_1/system_microblaze_0_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_microblaze_0_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
