# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/openfpga/Desktop/project/golden/example3/project_1.srcs/sources_1/bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
# IP: The module: 'system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/openfpga/Desktop/project/golden/example3/project_1.gen/sources_1/bd/system/ip/system_lmb_bram_1/system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/openfpga/Desktop/project/golden/example3/project_1.srcs/sources_1/bd/system/ip/system_lmb_bram_1/system_lmb_bram_1.xci
# IP: The module: 'system_lmb_bram_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/openfpga/Desktop/project/golden/example3/project_1.gen/sources_1/bd/system/ip/system_lmb_bram_1/system_lmb_bram_1_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_lmb_bram_1'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
