# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/openfpga/Desktop/project/golden/example9_3/project_1.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
# IP: The module: 'system_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/openfpga/Desktop/project/golden/example9_3/project_1.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/openfpga/Desktop/project/golden/example9_3/project_1.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/openfpga/Desktop/project/golden/example9_3/project_1.srcs/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xci
# IP: The module: 'system_axi_timer_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/openfpga/Desktop/project/golden/example9_3/project_1.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/openfpga/Desktop/project/golden/example9_3/project_1.gen/sources_1/bd/system/ip/system_axi_timer_0_0/system_axi_timer_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_timer_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
