
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2024.1
* DO NOT EDIT.
*
* Copyright (C) 2010-2024 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xhwicap.h"

/*
* The configuration table for devices
*/

XHwIcap_Config XHwIcap_ConfigTable[XPAR_XHWICAP_NUM_INSTANCES] =
{
	{
		XPAR_AXI_HWICAP_0_DEVICE_ID,
		XPAR_AXI_HWICAP_0_BASEADDR,
		XPAR_AXI_HWICAP_0_ICAP_DWIDTH,
		XPAR_AXI_HWICAP_0_MODE
	}
};


